// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactsManager.Inferastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260622222015_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("7c9e6645-3677-448a-95b7-511b41f17491"),
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = new Guid("a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("4a91b323-6902-4d3e-b147-3a2f6990c254"),
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryId = new Guid("99c6a23d-8d1e-4e90-95b6-03b576c75f71"),
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = new Guid("f2345b12-1111-4a55-89cc-5521aabbccdd"),
                            CountryName = "Brazil"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("NewsLetter")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("CountryId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("12345678-90ab-cdef-1234-567890abcdef"),
                            CountryId = new Guid("7c9e6645-3677-448a-95b7-511b41f17491"),
                            DateOfBirth = new DateTime(1996, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Alice",
                            phone = "1111111111"
                        },
                        new
                        {
                            PersonId = new Guid("23456789-0abc-def1-2345-67890abcdefa"),
                            CountryId = new Guid("a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6"),
                            DateOfBirth = new DateTime(2001, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Bob",
                            phone = "2222222222"
                        },
                        new
                        {
                            PersonId = new Guid("34567890-abcd-ef12-3456-7890abcdefa1"),
                            CountryId = new Guid("4a91b323-6902-4d3e-b147-3a2f6990c254"),
                            DateOfBirth = new DateTime(1991, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "Charlie",
                            phone = "3333333333"
                        },
                        new
                        {
                            PersonId = new Guid("4567890a-bcde-f123-4567-890abcdefa12"),
                            CountryId = new Guid("99c6a23d-8d1e-4e90-95b6-03b576c75f71"),
                            DateOfBirth = new DateTime(1998, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Name = "David",
                            phone = "4444444444"
                        },
                        new
                        {
                            PersonId = new Guid("567890ab-cdef-1234-5678-90abcdefa123"),
                            CountryId = new Guid("f2345b12-1111-4a55-89cc-5521aabbccdd"),
                            DateOfBirth = new DateTime(2004, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Name = "Eve",
                            phone = "5555555555"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.HasOne("Entities.Country", "Country")
                        .WithMany("Persons")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
