name: CI

on:
  workflow_dispatch:  
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - review_requested
      - synchronize
      - reopened    

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      checks: write
      pull-requests: write

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4  
        with:
          global-json-file: ContactsManager.UI/global.json 
          cache: true
          cache-dependency-path: 'ContactsManager.UI/**/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore --locked-mode --disable-build-servers -p:UseMultiToolProvider=false
        working-directory: ContactsManager.UI 

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          dotnet_format: true    

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: run-linters 

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4  
        with:
          global-json-file: ContactsManager.UI/global.json 
          cache: true
          cache-dependency-path: 'ContactsManager.UI/**/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore --locked-mode --disable-build-servers -p:UseMultiToolProvider=false
        working-directory: ContactsManager.UI 

      - name: Build
        run: dotnet build --no-restore
        working-directory: ContactsManager.UI

  test:
    name: Run All Tests & Upload Reports
    runs-on: ubuntu-latest
    needs: build 

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4  
        with:
          global-json-file: ContactsManager.UI/global.json 
          cache: true
          cache-dependency-path: 'ContactsManager.UI/**/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore --locked-mode --disable-build-servers -p:UseMultiToolProvider=false
        working-directory: ContactsManager.UI 

      - name: Run Specified Unit and Integration Tests
        run: |
          dotnet test Tests/ContactsManger.ServiceTests.csproj --configuration Release --logger "trx;LogFileName=ServiceTests.trx" --results-directory ./TestResults
          dotnet test ContactsManager.ControllersTest/ContactsManager.ControllersTest.csproj --configuration Release --logger "trx;LogFileName=ControllersTest.trx" --results-directory ./TestResults
   #       dotnet test ContactsManager.IntegrationTests/ContactsManager.IntegrationTests.csproj --configuration Release --logger "trx;LogFileName=IntegrationTests.trx" --results-directory ./TestResults

      - name: Upload all test results
        uses: actions/upload-artifact@v4
        with:
          name: All-Test-Results
          path: TestResults/
          retention-days: 7

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          file: ./ContactsManager.UI/Dockerfile
          push: false
          tags: contacts-manager-ui:${{ github.sha }}