name: CI

on:
  workflow_dispatch:  
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - review_requested
      - synchronize
      - reopened    

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4  
      with:
        global-json-file: ContactsManager.UI/global.json 
        cache: true
        cache-dependency-path: 'ContactsManager.UI/**/packages.lock.json'

    - name: Restore dependencies
      run: dotnet restore --locked-mode --disable-build-servers -p:UseMultiToolProvider=false
      working-directory: ContactsManager.UI 

    - name: Build
      run: dotnet build --no-restore
      working-directory: ContactsManager.UI

   # - name: Test
    #  run: dotnet test --no-build --verbosity normal
     # working-directory: ContactsManager.UI